version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile 
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cicd_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: always

  db:
    image: postgres:15
    container_name: cicd-db
    restart: always
    environment:
      POSTGRES_DB: cicd_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
