apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-server  # replace with actual image name
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres:5432/cicd_db
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              value: postgres
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest
          volumeMounts:
            - name: cicd
              mountPath: /mnt/pipeline
      volumes:
        - name: cicd
          persistentVolumeClaim:
            claimName: cicd
