apiVersion: v1
kind: Pod
metadata:
  name: cicd-pod
  labels:
    app: cicd
spec:
  containers:
    - name: rabbitmq
      image: rabbitmq:3-management
      ports:
        - containerPort: 5672
        - containerPort: 15672
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest

    - name: backend
      image: backend-server
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: DATABASE_URL
          value: jdbc:postgresql://host.minikube.internal:5432/cicd_db
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres
        - name: RABBITMQ_HOST
          value: localhost
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
      volumeMounts:
        - name: cicd-volume
          mountPath: /mnt/pipeline

    - name: worker
      image: cicd-worker
      imagePullPolicy: Never
      env:
        - name: DATABASE_URL
          value: jdbc:postgresql://host.minikube.internal:5432/cicd_db
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres
        - name: RABBITMQ_HOST
          value: localhost
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: guest
        - name: RABBITMQ_PASSWORD
          value: guest
      volumeMounts:
        - name: cicd-volume
          mountPath: /mnt/pipeline
        - name: docker-sock
          mountPath: /var/run/docker.sock

  volumes:
    - name: cicd-volume
      emptyDir: {}  # ✅ Replaced PVC with ephemeral volume
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
