apiVersion: v1
kind: PersistentVolume
metadata:
  name: cicd
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/pipeline/c213775b-6cda-4ead-b52f-b0afb675cb86"
