server:
  port: 8080  # Backend API will run on port 8080

spring:
  application:
    name: cicd-backend  # Name of the backend application

  main:
    allow-circular-references: true  # Allow circular references in Spring beans

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:54321/cicd_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:Li930227}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Change to 'update' in dev, 'validate' in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

cicd:
  rabbitmq:
    job-queue: cicd-job-queue

logging:
  level:
    root: INFO  # Default logging level
    edu.neu.cs6510.sp25.t1: DEBUG  # Enable debugging for this project

worker:
  api:
    execute-url: http://localhost:8081/api/worker/execute
    cancel-url: http://localhost:8081/api/worker/cancel


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
