server:
  port: 8080  # Backend API will run on port 8080

spring:
  application:
    name: cicd-backend  # Name of the backend application

  main:
    allow-circular-references: true  # Allow circular references in Spring beans

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cicd_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgress}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Change to 'update' in dev, 'validate' in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO  # Default logging level
    edu.neu.cs6510.sp25.t1: DEBUG  # Enable debugging for this project

worker:
  api:
    execute-url: http://localhost:8081/api/worker/execute
    cancel-url: http://localhost:8081/api/worker/cancel


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
