server:
  port: 8080  # Backend API will run on port 8080

spring:
  application:
    name: cicd-backend  # Name of the backend application

  main:
    allow-circular-references: true  # Allow circular references in Spring beans

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cicd_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:Li930227}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Change to 'update' in dev, 'validate' in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO  # Default logging level
    edu.neu.cs6510.sp25.t1: DEBUG  # Enable debugging for this project

worker:
  api:
    url: http://localhost:8081/api/worker  # Added worker API URL

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
