pipeline:
  name: simple-pipeline
  stages:
    - build
    - test
    - deploy
job:
  - name: job1
    stage: build
    image: node:16
    script:
      - echo "job1"
    needs:
      - job2

  - name: job2
    stage: test
    image: node:16
    script:
      - echo "job2"
    needs:
      - job3

  - name: job3
    stage: deploy
    image: node:16
    script:
      - echo "job3"
    needs:
      - job1