pipeline:
  name: direct-cycle
  stages:
    - build
    - test
jobs:
  - name: job1
    stage: build
    image: node:16
    script:
      - echo "job1"
    needs:
      - job2

  - name: job2
    stage: test
    image: node:16
    script:
      - echo "job2"
    needs:
      - job1