
pipeline:
  name: "Multi-Path Dependencies Pipeline"

  stages:
    - build
    - test
    - docs

jobs:
  job1:
    name: "Build Frontend"
    dependencies:
      - "job4"
      - "job5"
    script: "npm build"

  job2:
    name: "Build Backend"
    dependencies:
      - "job1"
      - "job3"
    script: "gradle build"

  job3:
    name: "Database Migration"
    dependencies:
      - "job4"
      - "job6"
    script: "flyway migrate"

  job4:
    name: "Code Quality Check"
    dependencies:
      - "job2"
    script: "sonar-scanner"

  job5:
    name: "Unit Tests"
    dependencies:
      - "job6"
    script: "npm test"

  job6:
    name: "Config Validation"
    dependencies:
      - "job2"
    script: "validate-config"