pipeline:
  name: "Multi-Path Dependencies Pipeline"
  stages:
    - build
    - test
    - docs

jobs:
  - name: "Build Frontend"
    stage: build
    image: node:16
    script:
      - "npm build"
    needs:
      - "Code Quality Check"
      - "Unit Tests"

  - name: "Build Backend"
    stage: build
    image: node:16
    script:
      - "gradle build"
    needs:
      - "Build Frontend"
      - "Database Migration"

  - name: "Database Migration"
    stage: test
    image: node:16
    script:
      - "flyway migrate"
    needs:
      - "Code Quality Check"
      - "Config Validation"

  - name: "Code Quality Check"
    stage: test
    image: node:16
    script:
      - "sonar-scanner"
    needs:
      - "Build Backend"

  - name: "Unit Tests"
    stage: test
    image: node:16
    script:
      - "npm test"
    needs:
      - "Config Validation"

  - name: "Config Validation"
    stage: docs
    image: node:16
    script:
      - "validate-config"
    needs:
      - "Build Backend"