name: my-cicd-pipeline
stages:
  - build
  - test
  - doc
  - deploy

jobs:
  - name: "compile"
    dockerImage: "openjdk:21-jdk-slim"
    script:
      - "javac -d out src/main/java/**/*.java"
    allowFailure: true
    stage: "build"
    workingDir: "usr/cs.java"

  - name: "unit-tests"
    dockerImage: "openjdk:21-jdk-slim"
    script:
      - "./gradlew test"
    allowFailure: true
    stage: "test"
    workingDir: "src/"
    dependencies: ["compile"]

  - name: "integration-tests"
    dockerImage: "openjdk:21-jdk-slim"
    script:
      - "./gradlew integrationTest"
    allowFailure: true
    stage: "test"
    workingDir: "src/"
    dependencies: ["compile"]

  - name: "generate-docs"
    dockerImage: "openjdk:21-jdk-slim"
    script:
      - "javadoc -d docs/ src/main/java/**/*.java"
    allowFailure: true
    stage: "doc"
    workingDir: "usr/cs.java"
    dependencies: ["compile"]

  - name: "build-jar"
    dockerImage: "gradle:8.12-jdk21"
    script:
      - "./gradlew bootJar"
    allowFailure: false
    stage: "deploy"
    workingDir: "."
    dependencies: ["compile", "unit-tests"]

  - name: "dockerize"
    dockerImage: "docker:latest"
    script:
      - "docker build -t my-cicd-app ."
      - "docker run -d -p 8080:8080 my-cicd-app"
    allowFailure: true
    stage: "deploy"
    workingDir: "."
    dependencies: ["build-jar"]