name: my-cicd-pipeline

stages:
  - name: "build"
    jobs:
      - name: "compile"
        dockerImage: "openjdk:21-jdk-slim"
        script:
          - "javac -d out src/main/java/**/*.java"
        allowFailure: true

      - name: "unit-tests"
        dockerImage: "openjdk:21-jdk-slim"
        script:
          - "./gradlew test"
        allowFailure: true

  - name: "package"
    jobs:
      - name: "build-jar"
        dockerImage: "gradle:8.12-jdk21"
        script:
          - "./gradlew bootJar"
        allowFailure: true

  - name: "deploy"
    jobs:
      - name: "dockerize"
        dockerImage: "docker:latest"
        script:
          - "docker build -t my-cicd-app ."
          - "docker run -d -p 8080:8080 my-cicd-app"
        allowFailure: false
