name: my-cicd-pipeline

stages:
  - name: "build"
    jobs:
      - name: "compile"
        dockerImage: "openjdk:21-jdk-slim"
        script:
          - "javac -d out src/main/java/**/*.java"
        allowFailure: false

      - name: "unit-tests"
        dockerImage: "openjdk:21-jdk-slim"
        script:
          - "./gradlew test"
        dependencies: ["compile"]  # ✅ Changed 'needs' → 'dependencies'
        allowFailure: false

  - name: "package"
    jobs:
      - name: "build-jar"
        dockerImage: "gradle:8.12-jdk21"
        script:
          - "./gradlew bootJar"
        dependencies: ["unit-tests"]  # ✅ Changed 'needs' → 'dependencies'
        allowFailure: false

  - name: "deploy"
    jobs:
      - name: "dockerize"
        dockerImage: "docker:latest"
        script:
          - "docker build -t my-cicd-app ."
          - "docker run -d -p 8080:8080 my-cicd-app"
        dependencies: ["build-jar"]  # ✅ Changed 'needs' → 'dependencies'
        allowFailure: false
