name: my-cicd-pipeline

stages:
  - build
  - test
  - doc
  - deploy

jobs:
  - name: "compile"
    dockerImage: "openjdk:21-jdk-slim"
    script:
      - "find cli/src/main/java -name '*.java' | xargs javac -d out"
    allowFailure: true
    stage: "build"
    workingDir: "C:/Users/Ree Li/desktop/neu/cs6510/t1-cicd"

  - name: "unit-tests"
    dockerImage: "openjdk:21-jdk-slim"
    script:
      - "./gradlew test"
    allowFailure: true
    stage: "test"
    workingDir: "C:/Users/Ree Li/desktop/neu/cs6510/t1-cicd"
    dependencies: ["compile"]

  - name: "generate-docs"
    dockerImage: "openjdk:21-jdk-slim"
    script:
      - "javadoc -d docs/ src/main/java/**/*.java"
    allowFailure: true
    stage: "doc"
    workingDir: "C:/Users/Ree Li/desktop/neu/cs6510/t1-cicd"
    dependencies: ["compile"]

  - name: "build-jar"
    dockerImage: "gradle:8.12-jdk21"
    script:
      - "./gradlew bootJar"
    allowFailure: true
    workingDir: "C:/Users/Ree Li/desktop/neu/cs6510/t1-cicd"
    stage: "deploy"
    dependencies: ["compile", "unit-tests"]

  - name: "dockerize"
    dockerImage: "docker:latest"
    script:
      - "docker build -t my-cicd-app ."
      - "docker run -d -p 8080:8080 my-cicd-app"
    allowFailure: true
    workingDir: "C:/Users/Ree Li/desktop/neu/cs6510/t1-cicd"
    stage: "deploy"
    dependencies: ["build-jar"]