name: my-cicd-pipeline

stages:
  - name: "build"
    jobs:
      - name: "compile"
        image: "openjdk:21-jdk-slim"
        script:
          - "javac -d out src/main/java/**/*.java"
        allowFailure: false

      - name: "unit-tests"
        image: "openjdk:21-jdk-slim"
        script:
          - "./gradlew test"
        needs: ["compile"]
        allowFailure: false

  - name: "package"
    jobs:
      - name: "build-jar"
        image: "gradle:8.12-jdk21"
        script:
          - "./gradlew bootJar"
        needs: ["unit-tests"]
        allowFailure: false

  - name: "deploy"
    jobs:
      - name: "dockerize"
        image: "docker:latest"
        script:
          - "docker build -t my-cicd-app ."
          - "docker run -d -p 8080:8080 my-cicd-app"
        needs: ["build-jar"]
        allowFailure: false
