name: "Test Dependencies Pipeline"
stages:
  - name: "build"
  - name: "test" 
  - name: "deploy"
jobs:
  - name: "compile"
    stage: "build"
    dockerImage: "openjdk:21-jdk-slim"
    script:
      - "javac -d out src/main/java/**/*.java"
    
  - name: "assemble"
    stage: "build"
    dockerImage: "gradle:8.12-jdk21"
    script:
      - "./gradlew assemble"
    dependencies:
      - "compile"
      
  - name: "unit-tests"
    stage: "test"
    dockerImage: "openjdk:21-jdk-slim"
    script:
      - "./gradlew test"
    dependencies:
      - "assemble"
      
  - name: "integration-tests"
    stage: "test"
    dockerImage: "openjdk:21-jdk-slim"
    script:
      - "./gradlew integrationTest"
    dependencies:
      - "unit-tests"
      
  - name: "package"
    stage: "deploy"
    dockerImage: "gradle:8.12-jdk21"
    script:
      - "./gradlew bootJar"
    dependencies:
      - "integration-tests"
      
  - name: "deploy"
    stage: "deploy"
    dockerImage: "docker:latest"
    script:
      - "docker build -t app ."
      - "docker run app"
    dependencies:
      - "package"