pipeline:
  name: 1
  stages:
    - build
    - test
    - docs

jobs:
  - name: compile
    stage: build
    image: gcc:latest
    script:
      - make clean
      - make all

  - name: unit-tests
    stage: test
    image: python:3.9
    script:
      - python -m pytest tests/
      - python -m coverage report

  - name: generate-docs
    stage: docs
    image: sphinx:latest
    script:
      - sphinx-build -b html docs/ build/html/